dvdrentals:
  target: dev
  outputs:
    dev:
      type: redshift
      method: iam
      host: redshift-serverless-workgroup.396768596145.us-west-2.redshift-serverless.amazonaws.com
      port: 5439
      database: dev
      workgroup: redshift-serverless-workgroup
      schema: starschema
      region: us-west-2
      threads: 1
      iam_profile: default
      user: admin
      is_serverless: true
      serverless_work_group: redshift-serverless-workgroup
