name: dvdrentals

profile: dvdrentals

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dvdrentals:
    +static_analysis: strict
    # Materialize all models in the starschemamodel subdirectory as views
    starschemamodel:
      +materialized: table