name: dvdrentals

profile: dvdrentals

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  dvdrentals:
    +schema: raw

models:
  dvdrentals:
    +static_analysis: strict
    # Materialize all models in the starschemamodel subdirectory as views
    starschemamodel:
      +materialized: table